.github/workflows/secrets-scan.yml
Makefile
README.MD
hooks/pre-commit

This PR adds a Bash script to run `gitleaks` and a Github Action that also runs `gitleaks` on every commit.

Secrets detection

---

.github/workflows/secrets-scan.yml
workflow-templates/secrets-scan.properties.json
workflow-templates/secrets-scan.svg
workflow-templates/secrets-scan.yml

Also point the workflow to the action in master.

feat(secrets-scan): add workflow template for secrets scanning

---

workflow-templates/library-checks-and-release.json
workflow-templates/library-checks-and-release.properties.json
workflow-templates/library-checks-and-release.yml

Following doc: https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

feat(fear-726): expose new shared library template

---

.github/workflows/go-lint-workflow.yaml

Last minute changes never work 🤦 
using `awk` instead of `cut` in the `Parse repository name` step

fix: BEAR-2859 fix lint badge

---

reusable-workflows/fortify-on-demand/workflow.yaml

The previous PR (#29) had a wrong symlink. This PR fixes it.

fix(SP-1466): fixing symlink

---

.github/workflows/ci-standard-checks.yml
.github/workflows/send-deployment-event.yml
CONTRIBUTING.MD
workflow-templates/library-checks-and-release.yml
workflow-templates/secrets-scan.yml
workflow-templates/send-deployment-event.yml

chore: renaming to main

---

.github/workflows/release.yaml

Adding a workflow to release `v1` version manually.

build(SP-1422): workflow to git tag v1

---

.github/workflows/go-lint-workflow.yaml

Upgrade Go and golangci-lint versions in the `go-lint-workflow`

feat(BEAR-3197): upgrade Go and golangci-lint versions

---

workflow-templates/ci-standard-checks.yml

Update the template to use the new shared workflow

feat(PR-41) update the CI standard checks template

---

CODEOWNERS

Updates CODEOWNER from Typeform/product-infrastructure to Typeform/platform-infra
[_Created by Sourcegraph batch change `platform/product-infrastructure-codeowner`._](https://sourcegraph.tools.typeform.tf/users/platform/batch-changes/product-infrastructure-codeowner)

[DEVTOOLS-1563] Updates CODEOWNERS to Typeform/platform-infra

---

.github/workflows/image-multiarch.yaml
reusable-workflows/image-multiarch/workflow.yaml

Added new workflow to build multi-arch images.
Tested here: https://github.com/Typeform/mercury/actions/runs/8437615026/job/23107977288?pr=108

feat(TU-10158): build multi-arch images

---

.github/workflows/image-multiarch.yaml

fix: fix typo

---

.github/dependabot.yml
.github/workflows/comment-deploy-link.yaml

Introduces `dependabot` configuration for GitHub Actions
- Adds dependabot configuration to manage GH actions dependencies
- Bumps the versions of some shared GH actions

feat: add dependabot configuration

---

.github/workflows/go-lint-workflow.yaml

Tested here: https://github.com/Typeform/tfcli/actions/runs/9093574187/job/24992788770?pr=490

feat(NOJIRA-123) Add timeout input to linter

---

.github/workflows/image-multiarch.yaml

Because latest tag is pushed last - it overwrites sha tag from image with run ID version

TU-16737 pushing sha only for version tag, no for latest

---

.github/workflows/go-lint-workflow.yaml

Sync with the versions required from https://www.notion.so/typeform/Use-supported-runtime-versions-4336ec1006ca4a9da53c6f57e914296e

feat(go-lint): update go and golangci-lint

---

CODEOWNERS

Platform Infra, Security, and App-Infra are merging into one team

SSP-506 - Update CODEOWNERS

---

.github/workflows/plantuml.yml
reusable-workflows/plantuml/workflow.yml

JIRA: https://typeform.atlassian.net/browse/PLT-491
Make workflow from https://github.com/Typeform/.github/pull/113 reusable.

feat(plantuml): make workflow reusable

---

.github/workflows/deep-purple-checks.yml

Switches Deep Purple shared action to use Staging (to avoid conflicts with SLO runs)

feat(PLT-886): run deep purple checks against staging

---

.github/workflows/image-multiarch.yaml

Tested it on: https://github.com/Typeform/workspace-service/pull/543

fix(PLT-927) include version prefix for SHA tag

---

.github/workflows/deep-purple-checks.yml

- Use the new `yarn test:ci:all` command introduced in https://github.com/Typeform/deep-purple/pull/1095
- Actually merge, not overwrite existing reports (renamed reports in https://github.com/Typeform/deep-purple/pull/1095 as well)

feat(deep-purple-checks): report on all tests

---

.github/workflows/deep-purple-checks.yml

https://typeform.atlassian.net/browse/PLT-1096
Add Personal Access Token to support cleanup via global teardown (deleting forms from previous runs) on staging.

fix(deep-purple-checks): add PAT for global teardown

---

.github/workflows/go-lint-workflow.yaml

Changes the comment if linting issues are found so that:
- `golangci-lint` fixes the issues found
- uses the `main` branch as a reference so that only changes are inspected
- includes GitHub PAT and initialises git so that private packages can be downloaded in the Docker container on demand

chore(go-lint): [NOJIRA-1234] comment fix command
