Typeform/.github

shared-actions/secrets-scan/secrets-scan.sh
This is to make the files visible to containers that are running inside the dind self hosted runners. The volume was shared in https://github.com/Typeform/terraform-shared/pull/1288.
=> SETI-787: Generate config temp files inside $GITHUB_WORKSPACE

.github/workflows/secrets-scan.yml, workflow-templates/secrets-scan.yml
We introduced new secrets that are also available for public repos. We
should use those in the Secrets Scan workflows so that it works with
all repos and not only with private ones.
=> [SETI-944] Use GITLEAKS_ secrets in secret-scan workflows

shared-actions/secrets-scan/secrets-scan.sh
Adding `set -e` to exit on fail in ` shared-actions/secrets-scan/secrets-scan.sh` and also logging out from docker to avoid conflicts with actions that run after this one.
Edit: Adding also custom messages depending on `gitleaks` exit code. One of them indicating what to do if a secret is found (Notion link).
=> Secrets Detection: exit on failing and docker logout

shared-actions/secrets-scan/secrets-scan.sh
The `secrets-scan.sh` script was not returning the actual exit code from `gitleaks` execution. Now it does.
=> fix: exiting secrets scan script with gitleaks outcome

workflow-templates/library-checks-and-release.yml
Add PR hook for github action
Note that:
* so, it does all the commands for pushes against the “release” branches (master/next/etc.) and for pushes to branches having PR opened against those branches
* the trick is that the `yarn semantic-release` will only happen for push against release branches (by default, refer to [doc](https://semantic-release.gitbook.io/semantic-release/usage/configuration))
=> chore(fear-726): add PR hook for github action

.github/workflows/fod-sast-scan.yaml, reusable-workflows/fortify-on-demand/workflow.yaml
Creating a reusable workflow that zips the chosen files and directories and sends them to a Fortify on Demand instance. There, a Static Application Security Testing (SAST) test will be performed and reviewed by the Security team asynchronously.
An example usage:
```yaml
jobs:
FoD-SAST-Scan:
uses: Typeform/.github/.github/workflows/fod-sast-scan.yaml@v1
with:
fod_release_id: "12345"
files: src/ Dockerfile Makefile package.json yarn.lock
secrets:
FOD_USER: ${{ secrets.FOD_USER }}
FOD_PAT: ${{ secrets.FOD_PAT }}
```
=> feat(SP-1466): adding FoD reusable workflow

.github/workflows/go-lint-workflow.yaml
Upgrade golangci-lint version to v1.44.2
Related to https://github.com/Typeform/golang-builder/pull/40
=> BEAR-3367 Upgrade golangci-lint version

.github/workflows/go-lint-workflow.yaml
bumps golangci-lint to `1.45.2` and the go version used go `1.17.9`
=> feat(go-lint): bump golangci-lint BEAR-3488

CODEOWNERS
Update new owners of ci-standards-checks as it got transferred from Engineering Intelligence to DevTools Team
=> docs: [EINT-1873] update codeowners

.github/workflows/go-lint-workflow.yaml
Adds two new workflow inputs called `working-directory` and `only-new-issues`, which are then passed to `golangci-lint`; uses an absolute path when referencing `lint-config/`.
This enables using this workflow in monorepos where Go code is not at the repo root, like Blocks.
Here's [a GHA run failing before these changes](https://github.com/Typeform/blocks/runs/6350623742?check_suite_focus=true#step:9:28), and [another passing after these changes](https://github.com/Typeform/blocks/runs/6351071046?check_suite_focus=true#step:9:57).
=> chore(BLOCKS-897): accept working directory input for monorepos

.github/workflows/go-lint-workflow.yaml
Removes path interpolation from the `<repository>` replacement step in the Go Lint workflow, which fixes it for repos not using `working-directory` - but still allows its use.
=> chore(INT-3762): fix <repository> placeholder replace in go lint workflow

.github/workflows/fod-sast-scan.yaml, .github/workflows/go-lint-workflow.yaml
Updates GHA runners to ephemeral runners. For more info check [this](https://www.notion.so/typeform/Migration-to-Ephemeral-runners-ffd85bafaed44cfd8a0c135701c4a6a7)
[_Created by Sourcegraph batch change `bruno.ferreira/migrate-gha-runners-to-ephemeral`._](https://sourcegraph.tools.typeform.tf/users/bruno.ferreira/batch-changes/migrate-gha-runners-to-ephemeral)
=> build(NOJIRA-1234): migrate GHA runners to ephemeral

.github/workflows/go-lint-workflow.yaml
We are experiencing a weird behavior from the linter. I think it is related to the go version.
Check: https://github.com/Typeform/performance-analytics-api/actions/runs/2635979121
[it works](https://github.com/Typeform/performance-analytics-api/actions/runs/2636367429)
=> feat(PA-493): [go-lint-workflow] Allow set go version

.github/workflows/comment-deploy-link.yaml
This PR adds a feature to comment-deploy-link reusable workflow.
In Web team we have identified the need to add this feature to this workflow.
We want to keep the content in the PR to its minimun so every comment is meaningful.
In order to avoid a breaking change, this new feature is **OPTIONAL**. The only new thing that needs to be added to the *caller* workflow is a new input called `update-comment: true`
[You can see a draft PR where this new feature has been tested](https://github.com/Typeform/public-main-site/pull/2949)
=> feat(WEB-5896): add update comment capabilites to deploy links workflow

.github/workflows/comment-deploy-link.yaml
Adds new optional input `runs-on` for `comment-deploy-link` shared workflow
Defaults to previous value `fear-ephemeral`
🟢  Tested in `formsapi`: https://github.com/Typeform/forms-api/pull/549
=> chore: runs-on optional input ARCH-97

.github/workflows/fod-sast-scan.yaml
[Github is deprecating the usage of NodeJS 12 in Github Actions](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). This PR updates the Github Actions used by the workflow `fod-sast-scan.yaml` which use NodeJS 12.
The PR has been tested in this [sampler branch](https://github.com/Typeform/sampler/tree/SEC-4091-update-node-actions) with [success](https://github.com/Typeform/sampler/actions/runs/4054073574/).
=> chore(SEC-4091): update steps in fod that use node 12

.github/workflows/go-lint-workflow.yaml
Bump some shared actions to newer versions already using node16 ([see here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/))
Remove `set-ouput` usages, as it's being deprecated ([see here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))
⚠️ Tested in formsapi. We went from 10 warnings to just 1 (probably a use of `set-output` from a dependency that hasn't been updated yet)
=> chore: bump shared actions ARCH-118

.github/workflows/go-lint-workflow.yaml
Follow our detailed thought process here: https://typeform.slack.com/archives/C2C0NBBJS/p1675255536771549
TL;DR: 
The default linter and go versions are (very) outdated; teams have moved up their go version once they could, and they should continue to have that freedom, which is why we do not want to touch the linter workflow's go version right now. The old default linter version does not work well with new go versions (see https://github.com/golangci/golangci-lint-action/issues/545), so we want to update the golangci-lint default to its newest version. With this change, we are betting (a hedged bet, since I made a couple of tests) that golangci-lint is fully backwards-compatible.
In the unexpected case (I did some tests) that this would break workflows of other teams, we'll rollback and …
=> chore(golangci-lint): Update default version to v1.51.0 (ARCH-121)

shared-actions/godoc-to-html/Dockerfile, shared-actions/godoc-to-html/README.md, shared-actions/godoc-to-html/action.yml, shared-actions/godoc-to-html/entrypoint.sh
**Summary**
This PR includes a new action to generate HTML go docs from a Go repository.
It automatically searches the `go.mod` file, builds the go docs, and downloads all the pages, linking them properly.
It creates a new `godocs` directory in the GH workspace with all the documentation.
**Usage example**
In `blocks`, we use the `godoc-to-html` action, deploy a preview with `surge.sh` and deploy the end version to GitHub pages, as you can see here: https://github.com/Typeform/blocks/pull/1340
The output: https://typeform.design/blocks/godocs/go.html
**Pending**
=> feat(NOJIRA-1234): Add new godoc to html action

.github/workflows/combine-prs.yml
This workflow allows merging multiple (dependabot) branches / pull requests into one. Always rebased on latest master.
=> feat(NOJIRA-1): Workflow to combine PRs

.github/workflows/go-lint-workflow.yaml
The current go versions we specify as default versions for the linter are so very old that they are not even supported any longer. Updating it to golang v1.19, because that is the oldest supported version.
Note that these are the _default_ versions, if there is any case that a service needs to use an older go version, one can overwrite the defaults like this: 
```
with:
go-version: "1.20.5"
golangci-lint-version: "v1.53.2"
```
(example: https://github.com/Typeform/forms-api/blob/b9383c8234dad5a8c19478ed5e01de5d2a0c5eef/.github/workflows/lint.yaml#L12)
See also https://www.notion.so/typeform/Use-supported-runtime-versions-4336ec1006ca4a9da53c6f57e914296e#fce1c1bce18b4e61b834440907dc0ba9 for some additional information and motivation.
See also …
=> feat(golint): Update default go version to v1.19.11

.github/workflows/ci-standard-checks.yml
Since `additionalChecks` was implemented in `ci-standard-checks`, some checks only run on PRs that are marked as "Ready for review" and are ignored on Draft PRs.
This means that for PRs that are opened in Draft and then marked as Ready for review without adding any new commits, CI Standard Checks will never execute `additionalChecks`.
This PR adds the `ready_for_review` PR event type to the CI Standard Checks workflow template.
=> fix(NOJIRA-123): trigger ci-standard-checks on draft->ready PR transition

.github/workflows/comment-deploy-link.yaml
This commit fixes the GitHub Action so that it prevents that a pull request title containing the ` character breaks.
This is fixed by reading these values (branch and pr title) as strings from environment variables instead of interpolating these in the script, as recommented by
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
This screenshot belongs to this [failed job](https://github.com/Typeform/smart-insights/actions/runs/6048827159/job/16415419029?pr=28)
=> [NOJIRA-123] fix(comment-deploy-link): do not break when a single quote is on title

.github/workflows/ci-standard-checks-workflow.yaml, reusable-workflows/ci-standard-checks/workflow.yaml
Add a new workflow for CI standard checks. We will use it to use the 50k free minutes we have with Github.
https://typeform.slack.com/archives/CCWDN8ASJ/p1704726455798989
=> feat(PR-41): add a shared CI standard checks workflow

.github/workflows/go-lint-workflow.yaml
Using `bear` runners (which are quite beefy) to run the linting workflow seems overkill, moreover since this workflow is usually ran in parallel to the actual build/test/deploy workflows, it is not critical that it runs as fast as possible.  
Actions were updated and although major version changes, don't seem to have breaking changes.
=> chore(PR-41): use automated-checks runner on go lint workflow and update actions

.github/workflows/comment-deploy-link.yaml
This workflow does not need to run on a self-hosted runner, since it only creates a comment in the PR. It frees up space for more heavy workflows to use the self-hosted runners.
=> chore(PR-1): run comment-deploy-link on ubuntu-latest

.github/workflows/go-lint-workflow.yaml
Some of the workflows are caching the `vendor` folder and `golangci-lint` is linting it, which it shouldn't. By skipping it, we will see an improvement in the worfklow run times for those projects :)
=> chore(PR-41): skip vendor folder in go lint workflow

.github/workflows/go-lint-workflow.yaml
Disable caching which was enabled by default in version `v4`, so we can keep the same behaviour as before.
=> fix(PR-41): disable caching in setup-go

.github/workflows/ci-standard-checks-workflow.yaml
Since we are using a latest ubuntu version, we need to specify the proper node version
A new ci-standard-checks version has already been released, with support for node 20 (see https://github.com/Typeform/ci-standard-checks/pull/175)
Tested in toltec: https://github.com/Typeform/toltec/pull/437
Fixes the following problem
=> feat: workflow to start using node20 AI-1061

.github/workflows/image-multiarch.yaml
Updaing the GHA workflow to use the new naming convention and remove the bear notation, as per: https://www.notion.so/typeform/GHA-graviton-migration-42535d1facd0404cac2f628ec92d4b06
=> feat(workflow): update runner to rename bear to ci-base

.github/workflows/go-lint-workflow.yaml
- bumps `golangci/golangci-lint-action` to `v4`
- increases default timeout (1m) to `3m`
=> feat(lint): bump action version and timeout

.github/workflows/go-lint-workflow.yaml
This workflow runs fine on the tested repositories and while the time it takes to run was observed to be a bit slower than the self-hosted runner, it shouldn't impact DX as this workflow still takes roughly (but often less than) ~2min to run.
=> feat(go-lint-workflow): run using GH hosted runner ubuntu

.github/dependabot.yml
Prefix dependabot commits/PRs with `fix` instead of `chore`, s.t. running the release action will create a new release/tag for this package. This is needed so that all consuming repositories get dependent GHA updates.
=> fix(dependabot): prefix with fix to trigger releases

.github/workflows/go-lint-workflow.yaml
- Go bumped to 1.23.1
- golangci-lint bumped to 1.61.0
This fixes issues between the old linter and newer version of Go (1.23).
=> [PRODINOPS-450] Bump golangci-lint and Go versions

.github/workflows/ci-standard-checks-workflow.yaml
For testing purposes before publishing `Typeform/ci-standards-checks` to `@v1` it would be nice to be able to test whether the newest update would break something.
Because repositories reference the workflow, not the `Typeform/ci-standards-check`, this was only possible when updating the workflow, which is a bit inconvenient.
We cannot pass in an arbitrary version, as GHA do not allow that in `uses`.
=> fix(ci-standards-check): allow to use beta version in workflow

.github/workflows/ci-standard-checks-workflow.yaml
Ironically, exactly the kind of error the previous PR was trying to avoid.
https://github.com/Typeform/.github/pull/107
=> fix(ci-standard-checks): fix check for usebeta

.github/workflows/ci-standard-checks-workflow.yaml, .github/workflows/test-ci-standard-checks-workflow.yaml
https://typeform.atlassian.net/browse/PLT-1
After recent events, trying to make this me-proof, i.e., adding a run for the ci-standard-check that was changed in the same PR.
Part of this will be making the "Test CI standard check" check mandatory.
=> ci(ci-standard-checks): test new ci-standard-checks [PLT-1]

.github/workflows/test-ci-standard-checks-workflow.yaml
Need to give it a different name or the "Required status checks" UI does not find it.
=> ci(ci-standard-checks): rename job so it can be used in required checks

.github/workflows/plantuml.yml
JIRA: https://typeform.atlassian.net/browse/PLT-491
Doing a bit of house cleaning here. Several services are currently bloating their `.github/workflows` folder with this one. For posterity is best if we keep track of the workflow here and import it. I'll follow-up with updating the workflow in all other places.
=> feat(plantuml): add plantuml workflow for diagram image generation

.github/workflows/go-lint-workflow.yaml
We are now using the `localmodule` option on GCI, which doesn't require a search and replace like `prefix()` did.
=> [NOJIRA-42] Remove search and replace on golangci.yaml

.github/workflows/go-lint-workflow.yaml
`golangci/golangci-lint-action@v6` always verifies the local `.golangci.yaml`, there is no way to pass it a config file explicitly. It does not respect the one passed in `args`, which is only passed to `golangci-lint` command itself.
It is also not really necessary to check this file on every repo, as it is the same one, downloaded from `golang-builder`'s `main` branch. Therefore, will add this verification step to `golang-builder`'s CI, and pass `verify: false` in the `go-lint` standard linting flow here.
=> fix(golangci-lint): do not verify schema

.github/workflows/go-lint-workflow.yaml
Jira: https://typeform.atlassian.net/browse/PLT-827
Remove `--skip-dirs="(^|/)vendor($|/)" --issues-exit-code=1`.
- `--skip-dirs="(^|/)vendor($|/)"`:  This option is deprecated. `vendor` directory is anyway the default of `exclude-dirs-use-default` which defaults to `true`: https://golangci-lint.run/usage/configuration/#command-line-options
- `--issues-exit-code=1`: This is the default already.
=> fix(go-lint): remove args that are the default already

.github/workflows/create-github-release.yaml
https://typeform.atlassian.net/browse/PLT-909
Create a Github release automatically on each push to `main`.
We frequently forget this (see https://github.com/Typeform/.github/releases/tag/v1.8.0 which contains a lot of unrelated changes in one release), and it has no negative consequences, as all workflows are referenced with the `@v1` tag.
We still have to update the `v1` tag manually - we can keep doing it that way, or have some basic testing flow and push `v1` automatically after a GH release has been created.
=> ci: semantic github release on push to main

.github/workflows/graphql-generate-persisted-operations.yml, reusable-workflows/graphql-generate-persisted-operations/graphql-generate-persisted-operations.yml
Makes the shared action fail if updating AllowList fails - this will cause the PR to fail, which ensures that no new queries can make it to production code with first having been registered in GraphQL-BFF's AllowList
=> Improve shared action for updating GraphQL-BFF AllowList

.github/workflows/ci-standard-checks.yml
We are adding a merge queue into builder. This PR is adding `merge_group` event to the `ci-standard-checks` action.
=> feat(NOJIRA-1): add merge queue event on ci-standard-checks

.github/workflows/graphql-generate-persisted-operations.yml
**What’s Changed**
Added GH_TOKEN to the env: block of the update-allow-list job in the “Generate persisted operations” GitHub Actions workflow.
**Why**
•	Yarn was failing with the error:
`Error: Failed to replace env in config: ${GH_TOKEN}`
=> fix(PLT-1044): Yarn .npmrc Interpolation Error in CI

.github/workflows/deep-purple-checks.yml
https://typeform.atlassian.net/browse/PLT-2115
Allow passing in the app name for deep-purple-checks Github workflow explicitly.
Not all repositories define the frontend app name in the root package.json. This is for example the case for `bob-the-builder`, our builder frontend app. 
Passing the app name explicitly is more obvious and less error-prone than trying to find the correct app name in multiple package.json files.
=> feat(deep-purple-checks): allow to pass app name explicitly

.github/workflows/go-lint-workflow.yaml
Bumping the default golangci-lint to `1.64.8`, https://github.com/Typeform/golang-builder/pull/130
=> fix: bump default golangci-lint

.github/workflows/ci-standard-checks-workflow.yaml, .github/workflows/comment-deploy-link.yaml, .github/workflows/deep-purple-checks.yml, .github/workflows/go-lint-workflow.yaml, .github/workflows/graphql-generate-persisted-operations.yml, .github/workflows/image-multiarch.yaml
https://typeform.atlassian.net/browse/PLT-2282
Allow to configure the self-hosted runner name for the shared workflows.
Defaults to the originally harcoded values.
This allows per-repository runners, without breaking all other repositories' actions at once.
=> feat(image-multiarch): allow to configure self-hosted runner

.github/workflows/go-lint-workflow.yaml
https://typeform.atlassian.net/browse/PLT-2300
Make the configuration file location of golangci-lint (`golangci.yaml`) configurable.
This is a preparation for the move to golangci-lint v2. The configuration files between v1 and v2 are not compatible, which means that once we move the golangci-lint executable to `2.x`, a single location for the file is not sufficient, as some repos will be on v1, and others on v2.
The defaults are the hardcoded values from today, with the exception of `ref`, which is set to `1.15.0` (latest tag with a `v1` configuration file).
Tested for backwards compatibility: https://github.com/Typeform/event-dispatcher/actions/runs/17552732900/job/49848910468?pr=605
=> feat: dynamic golangci-lint versions and configuration
